
-- BOARD TABLE DROP & CREATE
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BID    NUMBER(6)        PRIMARY KEY,
    BNAME  VARCHAR2(50)   NOT NULL, -- 작성자 이름
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT VARCHAR2(1000),                      
    BDATE  DATE          DEFAULT SYSDATE NOT NULL, -- 작성시점
    BHIT   NUMBER(6)      DEFAULT 0 NOT NULL, -- 조회수
    BGROUP NUMBER(6)    NOT NULL, -- 글 그룹
    BSTEP  NUMBER(6)     NOT NULL, -- 글 그룹 내 출력 순서
    BINDENT NUMBER(6)   NOT NULL, -- 들여쓰기
    BIP     VARCHAR2(20) NOT NULL
);

-- DUMMY DATA
SELECT * FROM BOARD;

INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '글1', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '시나공', '글2', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.18');
    
    -- 1번글의 답변글
    INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, '김댓글', '글1-1', '답', 1, 1, 1, '118.168.10.18');
        
        
        

-- <<DAO에 들어갈 쿼리>>
-- 글 목록(startRow ~ endRow)
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;

SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 2 AND 3;

-- 전체 글 개수
SELECT COUNT(*) FROM BOARD;

-- 원글 쓰기
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '유재석', '글3', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.18.18');

-- BID로 조회수 올리기
UPDATE BOARD SET BHIT = BHIT + 1 WHERE BID = 1;

-- 글 상세보기 (BID로 DTO 가져오기)
SELECT * FROM BOARD WHERE BID = 1;

-- 답변글 쓰기 전 STEP A (기존의 답변글의 출력 순서를 +1)
SELECT * FROM BOARD WHERE BGROUP = 1; -- 1번 글 GROUP 출력
-- 이게 바로 stepA
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP = 1 AND BSTEP > 0;

-- 답변글 쓰기
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '홍답', '글1-2', NULL, 1, 1, 1, '12.45.0.1');

-- 글 수정
UPDATE BOARD SET BNAME = '김김김',
                 BTITLE = '수정글입니다.',
                 BCONTENT = '수정된 본문입니다.',
                 BIP = '1.1.1.1'
            WHERE BID = 2;
-- 글 삭제
DELETE FROM BOARD WHERE BID = 2;

COMMIT;












