
-- [ 문II ] 다음과 같은 구조의 테이블을 생성하고 
--         데이터를 입력 및 출력하는 SQL문을 조건에 맞게 작성하시오(40점).

-- 조건1. exERD 작성 - 첨부파일 확인 부탁드립니다.
-- 조건2. 테이블을 삭제하고 테이블을 생성하시오.
-- 조건3, 4. 테이블 필드별 제약조건

DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL (
    LEVELNO   NUMBER(10)   PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE CUSTOMER(
    CNO      NUMBER(10)   PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE    VARCHAR2(20) UNIQUE,
    POINT    NUMBER(20),
    LEVELNO  NUMBER(10) REFERENCES CUS_LEVEL(LEVELNO) 
);

-- 조건5. CUSTOMER 테이블의 CNO 시퀀스 CUS_SQ 생성
DROP SEQUENCE CUS_SQ;
CREATE SEQUENCE CUS_SQ NOCYCLE NOCACHE;

-- INSERT
-- CUS_LEVEL
INSERT INTO CUS_LEVEL VALUES(1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES(2, 'VIP');
INSERT INTO CUS_LEVEL VALUES(3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES(4, 'BLACK');

SELECT * FROM CUS_LEVEL;

-- CUSTOMER
INSERT INTO CUSTOMER 
    VALUES(CUS_SQ.NEXTVAL, '홍길동', TO_DATE('22/03/10', 'RR/MM/DD'), '010-9999-9999', 0, 1);
INSERT INTO CUSTOMER 
    VALUES(CUS_SQ.NEXTVAL, '이철수', TO_DATE('22/04/19', 'RR/MM/DD'), '010-8888-8888', NULL, 2);

SELECT * FROM CUSTOMER;

-- 조건6. 두개의 테이블의 내용을 이용하여 아래와 같이 출력되도록 SQL문 추가 작성
SELECT CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNAME
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO;

