-- 0428 Customer.sql

DROP TABLE CUSTOMER;
DROP SEQUENCE CUS_SEQ;

CREATE TABLE CUSTOMER (
    CNO    NUMBER(3)    PRIMARY KEY,
    CTEL   VARCHAR2(40) NOT NULL,
    CNAME  VARCHAR2(40) NOT NULL,
    CPOINT NUMBER(10)   DEFAULT 1000
);

CREATE SEQUENCE CUS_SEQ;

-- INSERT
INSERT INTO CUSTOMER VALUES (CUS_SEQ.NEXTVAL, '010-1111-1111', '홍길동', 1200);
INSERT INTO CUSTOMER VALUES (CUS_SEQ.NEXTVAL, '010-2222-1111', '마길동', 3000);
INSERT INTO CUSTOMER VALUES (CUS_SEQ.NEXTVAL, '010-2222-2222', '김길동', 2000);

SELECT * FROM CUSTOMER;
COMMIT;

-- 1. 가입 public int insertCustomer(CustomerDto dto)
INSERT INTO CUSTOMER VALUES (CUS_SEQ.NEXTVAL, '010-4444-4444', '신길동', 1300);

-- 2. 폰조회 : 폰뒤4자리, 전체로도 조회 가능
-- public ArrayList<CustomerDto> cTelgetCustomer(String ctel)
SELECT * FROM CUSTOMER
    WHERE CTEL LIKE '%'||'1111';

-- 3. 전체출력 public ArrayList<CustomerDto> getCustomers()
SELECT * FROM CUSTOMER;

COMMIT;