
-- 테이블 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL
);

-- 회원가입
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES ('bbb', '1', '홍길동', TO_DATE('1998-12-12', 'YYYY-MM-DD'));
    
select * from member;
commit;