
-- *테이블 생성 : 같은 이름의 테이블이 생성되었을 경우 DROP
-- 1. PERSON TABLE
DROP TABLE PERSON;
CREATE TABLE PERSON (
    pNO   NUMBER(3)    PRIMARY KEY,
    pNAME VARCHAR2(30) NOT NULL,
    jNO   NUMBER(3)    REFERENCES JOB(jNO),
    KOR   NUMBER(3),
    ENG   NUMBER(3),
    MAT   NUMBER(3)
    );

-- pNO SEQUENCE 생성    
DROP SEQUENCE PERSON_NO_SEQ;
CREATE SEQUENCE PERSON_NO_SEQ NOCYCLE NOCACHE;

-- 2. JOB TABLE 
DROP TABLE JOB;
CREATE TABLE JOB (
    jNO   NUMBER(3)    PRIMARY KEY,
    jNAME VARCHAR2(30) UNIQUE NOT NULL
);

-- *더미 데이터 삽입 ( JOB >> PERSON 순으로 )
-- JOB INSERT
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');

SELECT * FROM JOB;

-- PERSON INSERT
INSERT INTO PERSON VALUES(PERSON_NO_SEQ.NEXTVAL,'정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES(PERSON_NO_SEQ.NEXTVAL,'박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES(PERSON_NO_SEQ.NEXTVAL,'배수지', 20, 20, 90, 90);
INSERT INTO PERSON VALUES(PERSON_NO_SEQ.NEXTVAL,'설현', 20, 95, 95, 100);
INSERT INTO PERSON VALUES(PERSON_NO_SEQ.NEXTVAL,'송혜교', 10, 100, 100, 100);

SELECT * FROM PERSON;


-- 1번 : PNAME, JNAME, KOR, ENG, MAT 입력받아 INSERT
-- JNAME은 서브쿼리를 이용하여 입력받은 후 변형을 하여야 한다.
SELECT pNAME, jNAME, KOR, ENG, MAT
    FROM PERSON P, JOB J 
    WHERE P.jNO = J.jNO;

INSERT INTO PERSON VALUES 
    (PERSON_NO_SEQ.NEXTVAL, '전지현', (SELECT jNO FROM JOB WHERE jNAME = '배우'), 97, 99, 100);

-- 2번 : 등수, 이름(pNO), 직업명, 국어, 영어, 수학, 총점 출력
-- ORDER BY를 이용하여서 총점 큰 순으로 정렬
-- 직업명을 입력 받아야 함
SELECT pNAME ||'('||PNO||'번)' pNAME, jNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "SUM"
    FROM PERSON P, JOB J WHERE P.jNO = J.jNO AND JNAME = '배우';

SELECT ROWNUM RANK, A.*
    FROM (SELECT pNAME ||'('||PNO||'번)' pNAME, jNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "SUM"
    FROM PERSON P, JOB J WHERE P.jNO = J.jNO AND JNAME = '배우' ORDER BY SUM DESC) A;

-- 3번 : 모든 행의 등수, 이름, 직업명, 국어, 영어, 수학, 총점을 출력
-- (총점 기준으로 내림차순 정렬)

SELECT ROWNUM RANK, A.*
    FROM (SELECT pNAME ||'('||PNO||'번)' pNAME, jNAME, KOR, ENG, MAT, (KOR+ENG+MAT) "SUM"
    FROM PERSON P, JOB J WHERE P.jNO = J.jNO) A;
    
    commit;
    
-- 4번 콤보박스에 들어갈 직업명 list - VECTOR
SELECT JNAME FROM JOB;
    
    
    
    